export { default as Login } from "./Login/Login";
export { default as Register } from "./Register/Register";
export { default as Dashboard } from "./Dashboard/Dashboard";
export { default as AdminDashboard } from "./AdminDashboard/AdminDashboard";
export { default as ResetPassword } from "./ResetPassword/ResetPassword";
export { default as Onboarding } from "./Onboarding/Onboarding";
export { default as Signout } from "./Signout/Signout";
export { default as CreatePost} from "./CreatePost/CreatePost";
export { default as Post} from "./Post/Post";
export { default as Profile } from "./Profile/Profile";
export { default as EditProfile } from "./Profile/EditProfile";
