# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: [push, pull_request] 
  
  # to cancel previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    strategy:
      matrix:
        node-version: ${{ fromJSON(github.ref == 'refs/heads/main' && '[18.x]' || '[14.x,16.x,18.x]') }}
        os: ${{ fromJSON(github.ref == 'refs/heads/main' && '["ubuntu-latest"]' || '["ubuntu-latest", "windows-latest"]') }}
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: install dependencies 
      run: npm install

    - name: Build
      run: npm run build --if-present
  
  unit-tests:

    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: ${{ fromJSON(github.ref == 'refs/heads/main' && '[18.x]' || '[14.x,16.x,18.x]') }}
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:

    - name: Run Unit tests
      run: npm run test
  
  # for future
  # perf-tests:

  #   runs-on: ubuntu-latest
  #   needs: unit-tests

  #   strategy:
  #     matrix:
  #       node-version: [14.x, 16.x, 18.x]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
  #   if: github.ref == 'refs/heads/main'
  #   steps:

  #   - name: Run Perf tests
  #     run: npm run perf-test

