# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: [push, pull_request] 
  
  # to cancel previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test:

    strategy:
      matrix:
        node-version: ${{ fromJSON(github.ref == 'refs/heads/main' && '[18]' || '[16,18]') }}
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: 'ubuntu-latest'

    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: install dependencies 
      run: npm install

    - name: Build
      run: npm run build --if-present
    
    - name: Run Unit tests
      run: npm run test
  
  deploy_staging: 

    runs-on: 'ubuntu-latest'

    if: github.ref == 'refs/heads/main'
    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: install dependencies 
      run: npm install

    - name: Install Doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_ACCESS_TOKEN }}
    
    - name: Deploy
      run: doctl apps create-deployment ${{ secrets.APP_ID }} --wait=true

    # - name: Add IP address to trusted source postgres
    #   uses: GarreauArthur/manage-digital-ocean-managed-database-trusted-sources-gh-action@main
    #   with:
    #     action: "add"
    #     database_id: ${{ secrets.DATABASE_ID }}
    #     digitalocean_token: ${{ secrets.DO_ACCESS_TOKEN }}

    # - name: run E2E tests
    #   run: npm run test:e2e

    # - name: Remove IP address to trusted source postgres
    #   uses: GarreauArthur/manage-digital-ocean-managed-database-trusted-sources-gh-action@main
    #   with:
    #     action: "remove"
    #     database_id: ${{ secrets.DATABASE_ID }}
    #     digitalocean_token: ${{ secrets.DO_ACCESS_TOKEN }} 
  

  # for future
  # perf-tests:

  #   runs-on: ubuntu-latest
  #   needs: unit-tests

  #   strategy:
  #     matrix:
  #       node-version: [14.x, 16.x, 18.x]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
  #   if: github.ref == 'refs/heads/main'
  #   steps:

  #   - name: Run Perf tests
  #     run: npm run perf-test

  
    






